apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-wiki
  namespace: {{ .Release.Namespace }}
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-wiki
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-wiki
    spec:
      containers:
        - name: gollum
          image: suttang/gollum
          args: ["--base-path", "/gollum"]
          ports:
            - containerPort: 4567
          volumeMounts:
            - name: wiki
              mountPath: /root/wikidata
              subPath: {{ .Release.Name }}-gollum
          resources:
            requests:
              cpu: 100m
              memory: 128M
            limits:
              cpu: 1000m
              memory: 1024M
        - name: docsify
          image: littlstar/docker-docsify
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: wiki
              mountPath: /usr/local/docsify
              subPath: {{ .Release.Name }}-docsify
          resources:
            requests:
              cpu: 100m
              memory: 128M
            limits:
              cpu: 1000m
              memory: 1024M
      volumes:
        - name: wiki
        {{- if .Values.pv.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-storage-claim
        {{- else }}
          emptyDir: {}
        {{- end -}}