apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  namespace: {{ .Release.Namespace }}
spec:
  rules:
    - host: {{ .Values.hostname }}
      http:
        paths:
          - path: /gollum/
            backend:
              serviceName: {{ .Release.Name }}-wiki
              servicePort: 4567
          - path: /docsify/
            backend:
              serviceName: {{ .Release.Name }}-wiki
              servicePort: 3000
  {{- if .Values.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.hostname }}
      secretName: {{ .Release.Name }}-tls
  {{- end -}}